### ISSUE TITLE
My growstuff.org profile is all http 500 errors

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1079]
I added a new planting (lavender).
After submitting the form i get a http 500 error at http://www.growstuff.org/plantings/shiny-beside-the-garage-lavender

If i go to my plantings page, i also get a http 500 error.
http://www.growstuff.org/plantings/owner/shiny

Same error page on my profile:
http://www.growstuff.org/members/shiny

This happens when signed in, and when not signed in.

![image](https://cloud.githubusercontent.com/assets/12266/20646136/f6f40278-b4d9-11e6-9dd8-ad6b8fce2a5a.png)

Other parts of the site seem fine.

**Comment by Br3nda** [comment]
The garden page is also broken now http://www.growstuff.org/gardens/shiny-beside-the-garage

![image](https://cloud.githubusercontent.com/assets/12266/20646702/5efddd20-b4e5-11e6-9f8b-d2841f9720b6.png)

**Comment by CloCkWeRX** [comment]
Can anyone throw me access to newrelic, easier to hunt down errors like this via that.

**Comment by pozorvlak** [comment]
Logs from hitting http://growstuff.org/plantings/shiny-beside-the-garage-lavender:

```
2016-11-29T09:27:24.695957+00:00 app[web.1]: Started GET "/plantings/shiny-beside-the-garage-lavender" for 213.175.37.10 at 2016-11-29 09:27:24 +0000
2016-11-29T09:27:24.701516+00:00 app[web.1]: Processing by PlantingsController#show as HTML
2016-11-29T09:27:24.701568+00:00 app[web.1]:   Parameters: {"id"=>"shiny-beside-the-garage-lavender"}
2016-11-29T09:27:24.798810+00:00 app[web.1]:   Rendered plantings/show.html.haml within layouts/application (32.3ms)
2016-11-29T09:27:24.799200+00:00 app[web.1]: Completed 500 Internal Server Error in 97ms (ActiveRecord: 20.8ms)
2016-11-29T09:27:24.804171+00:00 app[web.1]: ActionView::Template::Error (undefined method `+' for nil:NilClass):
2016-11-29T09:27:24.804169+00:00 app[web.1]: 
2016-11-29T09:27:24.804172+00:00 app[web.1]:     43:         = " (#{sunniness})"
2016-11-29T09:27:24.804175+00:00 app[web.1]:     46:       %dd= "#{display_days_before_maturity(@planting)}"
2016-11-29T09:27:24.804173+00:00 app[web.1]:     44: 
2016-11-29T09:27:24.804176+00:00 app[web.1]:     47: 
2016-11-29T09:27:24.804174+00:00 app[web.1]:     45:       %dt Days until maturity:
2016-11-29T09:27:24.804176+00:00 app[web.1]:     48:       %dt Finished:
2016-11-29T09:27:24.804177+00:00 app[web.1]:     49:       %dd= "#{display_finished(@planting)}"
2016-11-29T09:27:24.804178+00:00 app[web.1]:   app/helpers/plantings_helper.rb:11:in `display_days_before_maturity'
2016-11-29T09:27:24.804180+00:00 app[web.1]:   app/controllers/plantings_controller.rb:35:in `show'
2016-11-29T09:27:24.804179+00:00 app[web.1]:   app/views/plantings/show.html.haml:46:in `_app_views_plantings_show_html_haml___4206401535551243686_70334624964160'
2016-11-29T09:27:24.804180+00:00 app[web.1]: 
2016-11-29T09:27:24.804181+00:00 app[web.1]: 
2016-11-29T09:27:25.109683+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=www.growstuff.org request_id=7f7c9df9-8dca-408a-9c74-ccf838f50333 fwd="213.175.37.10" dyno=web.1 connect=1ms service=8ms status=200 bytes=180
```

**Comment by pozorvlak** [comment]
The bug (well, at least one of the bugs) is in `plantings_helper`: https://github.com/Growstuff/growstuff/blob/dev/app/helpers/plantings_helper.rb#L11. When both `finished_at` and `planted_at` are nil, we get the `undefined method +` error shown above.

**Comment by pozorvlak** [comment]
@CloCkWeRX: I've added you as a "collaborator" on Heroku, which should give you access to NewRelic (and also to `heroku logs`).

**Comment by pozorvlak** [comment]
All the links above work now on production; closing.
