### ISSUE TITLE
500 error on post view

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1248]
Example:
http://www.growstuff.org/posts/shiny-20170128-some-of-features-id-like

**Comment by pozorvlak** [comment]
Relevant logs:

```
2017-02-28T10:48:01.984258+00:00 app[web.1]: Started GET "/posts/shiny-20170128-some-of-features-id-like" for 62.30.12.102 at 2017-02-28 10:48:01 +0000
2017-02-28T10:48:01.995340+00:00 app[web.1]: You are setting a key that conflicts with a built-in method OmniAuth::Strategy::Options#display defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
2017-02-28T10:48:01.997000+00:00 app[web.1]: Processing by PostsController#show as HTML
2017-02-28T10:48:01.997046+00:00 app[web.1]:   Parameters: {"id"=>"shiny-20170128-some-of-features-id-like"}
2017-02-28T10:48:02.021282+00:00 app[web.1]:   Rendered shared/_signin_signup.html.haml (0.4ms)
2017-02-28T10:48:02.022425+00:00 app[web.1]:   Rendered members/_avatar.html.haml (0.8ms)
2017-02-28T10:48:02.046910+00:00 app[web.1]:   Rendered posts/_single.html.haml (25.5ms)
2017-02-28T10:48:02.058004+00:00 app[web.1]: Read fragment views/crops/30-610-20170211170810/2ea61ca00099c11fe32f0c1e90da04d0 (1.6ms)
2017-02-28T10:48:02.058193+00:00 app[web.1]:   Rendered crops/_thumbnail.html.haml (5.9ms)
2017-02-28T10:48:02.061241+00:00 app[web.1]: Read fragment views/crops/37-610-20170211170810/2ea61ca00099c11fe32f0c1e90da04d0 (1.3ms)
2017-02-28T10:48:02.061382+00:00 app[web.1]:   Rendered crops/_thumbnail.html.haml (3.0ms)
2017-02-28T10:48:02.064793+00:00 app[web.1]: Read fragment views/crops/164-610-20170211170810/2ea61ca00099c11fe32f0c1e90da04d0 (1.4ms)
2017-02-28T10:48:02.064870+00:00 app[web.1]:   Rendered crops/_thumbnail.html.haml (3.3ms)
2017-02-28T10:48:02.067339+00:00 app[web.1]: Read fragment views/crops/216-610-20170211170810/2ea61ca00099c11fe32f0c1e90da04d0 (1.3ms)
2017-02-28T10:48:02.067545+00:00 app[web.1]:   Rendered crops/_thumbnail.html.haml (2.5ms)
2017-02-28T10:48:02.078481+00:00 app[web.1]:   Rendered members/_avatar.html.haml (3.1ms)
2017-02-28T10:48:02.078595+00:00 app[web.1]:   Rendered comments/_single.html.haml (5.6ms)
2017-02-28T10:48:02.078752+00:00 app[web.1]:   Rendered posts/_comments.html.haml (10.6ms)
2017-02-28T10:48:02.078901+00:00 app[web.1]:   Rendered posts/show.html.haml within layouts/application (60.1ms)
2017-02-28T10:48:02.079113+00:00 app[web.1]: Completed 500 Internal Server Error in 82ms (ActiveRecord: 23.2ms)
2017-02-28T10:48:02.081528+00:00 app[web.1]: 
2017-02-28T10:48:02.081530+00:00 app[web.1]: ActionView::Template::Error (undefined method `preferred_avatar_uri' for nil:NilClass):
2017-02-28T10:48:02.081531+00:00 app[web.1]:     1: = link_to image_tag(avatar_uri(member, 150),
2017-02-28T10:48:02.081534+00:00 app[web.1]:     2:           alt: '',
2017-02-28T10:48:02.081534+00:00 app[web.1]:     3:           class: 'img img-responsive avatar'),
2017-02-28T10:48:02.081535+00:00 app[web.1]:     4:   member_path(member)
2017-02-28T10:48:02.081536+00:00 app[web.1]:   app/helpers/application_helper.rb:58:in `avatar_uri'
2017-02-28T10:48:02.081537+00:00 app[web.1]:   app/views/members/_avatar.html.haml:1:in `_app_views_members__avatar_html_haml__1017746842609317473_70118043714360'
2017-02-28T10:48:02.081538+00:00 app[web.1]:   app/views/comments/_single.html.haml:5:in `_app_views_comments__single_html_haml__2034900492546986671_70118018995120'
2017-02-28T10:48:02.081538+00:00 app[web.1]:   app/views/posts/_comments.html.haml:6:in `block in _app_views_posts__comments_html_haml___4589369918271483096_70118019320960'
2017-02-28T10:48:02.081539+00:00 app[web.1]:   app/views/posts/_comments.html.haml:5:in `_app_views_posts__comments_html_haml___4589369918271483096_70118019320960'
2017-02-28T10:48:02.081540+00:00 app[web.1]:   app/views/posts/show.html.haml:42:in `_app_views_posts_show_html_haml__221050712719623082_70118021433660'
2017-02-28T10:48:02.081540+00:00 app[web.1]:   app/controllers/posts_controller.rb:21:in `show'
2017-02-28T10:48:02.081541+00:00 app[web.1]: 
2017-02-28T10:48:02.081542+00:00 app[web.1]: 
2017-02-28T10:48:02.081168+00:00 heroku[router]: at=info method=GET path="/posts/shiny-20170128-some-of-features-id-like" host=www.growstuff.org request_id=bcafa598-1a5f-4764-a1b6-4975b237c74b fwd="62.30.12.102" dyno=web.1 connect=1ms service=100ms status=500 bytes=871
```

**Comment by pozorvlak** [comment]
My fault again, I'm afraid. Your post had a spam comment on it. When I deleted the spammer's account I deleted all their posts, but obviously failed to delete all their comments too. I have now done so, and the post now renders properly.

**Comment by pozorvlak** [comment]
I have now deleted all comments without legitimate author_ids (they were all either spam or blank).

**Comment by pozorvlak** [comment]
Yes, I'm aware that running `rails c` on the production database is not good ops practice :-(

**Comment by maco** [comment]
My fault too then. I haven't been deleting comments either. I was thinking
posts and comments are the same thing, just one has a parent

**Comment by Br3nda** [comment]
We can make some database constraints to save from this mistake in the future.

**Comment by Br3nda** [comment]
@pozorvlak im' getting error on /notifications page too.. Are there messages from spammers there?

**Comment by maco** [comment]
so do i, and i'm gonna figure "probably"
