### ISSUE TITLE
Failures while running bundle exec rspec --only-failures

### ISSUE THREAD

**Issue by shadjachaudhari** [Growstuff/growstuff#1369]
Hello,
I am new to Ruby and would want to get the test cases passed.
Kindly help.
I am having following errors-

```
Failures:

  1) signup sign up for new account with existing username
     Failure/Error: first('.signup a').click # click the 'Sign up' button in the middle of the page
     
     NoMethodError:
       undefined method `click' for nil:NilClass
     # ./spec/features/signup_spec.rb:26:in `block (2 levels) in <top (required)>'

  2) signup sign up for new account without accepting TOS
     Failure/Error: first('.signup a').click # click the 'Sign up' button in the middle of the page
     
     NoMethodError:
       undefined method `click' for nil:NilClass
     # ./spec/features/signup_spec.rb:37:in `block (2 levels) in <top (required)>'

  3) signup with facebook sign up
     Failure/Error: first('.signup a').click
     
     NoMethodError:
       undefined method `click' for nil:NilClass
     # ./spec/features/signup_spec.rb:57:in `block (3 levels) in <top (required)>'

  4) Changing locales Locale can be set with a query param
     Failure/Error: expect(page).to have_content("a community of food gardeners.")
       expected to find text "a community of food gardeners." in "TypeError in Home#index Showing /home/shadja/Documents/ruby on rails/growstuff/app/views/layouts/_meta.html.haml where line #8 raised: no implicit conversion of nil into String Extracted source (around line #8): 6 7 8 9 10 11 - else = tag(\"meta\", property: \"og:image\", content: image_url('facebook-thumbnail.png')) = tag(\"meta\", property: \"og:title\", content: (content_for?(:title) ? yield(:title) + \" - \" : \"\") + ENV['GROWSTUFF_SITE_NAME']) = tag(\"meta\", property: \"og:type\", content: \"website\") = tag(\"meta\", property: \"og:url\", content: root_url) Trace of template inclusion: app/views/layouts/application.html.haml Rails.root: /home/shadja/Documents/ruby on rails/growstuff Application Trace | Framework Trace | Full Trace app/views/layouts/_meta.html.haml:8:in `+' app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_70240701838720' app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml__2096314005913121334_70240701925040' Request Parameters: None Toggle session dump Toggle env dump Response Headers: None"
     # ./spec/features/locale_spec.rb:8:in `block (2 levels) in <top (required)>'

  5) forums as an admin user navigating to forum admin with js
     Failure/Error: click_link member.login_name
     
     Capybara::ElementNotFound:
       Unable to find link "member150"
     # ./spec/features/admin/forums_spec.rb:25:in `block (3 levels) in <top (required)>'

  6) forums as an admin user navigating to forum admin without js
     Failure/Error: click_link "Admin"
     
     Capybara::ElementNotFound:
       Unable to find link "Admin"
     # ./spec/features/admin/forums_spec.rb:14:in `block (3 levels) in <top (required)>'

  7) crop search search results show the search term in title
     Failure/Error:
       within "form#navbar-search" do
         fill_in "term", with: "tomato"
         click_button "Search"
       end
     
     Capybara::ElementNotFound:
       Unable to find css "form#navbar-search"
     # ./spec/features/crops/crop_search_spec.rb:6:in `block (2 levels) in <top (required)>'

  8) footer has the Open Service link and graphic
     Failure/Error: expect(page).to have_selector 'a[href="http://opendefinition.org/ossd/"]'
       expected to find css "a[href=\"http://opendefinition.org/ossd/\"]" but there were no matches
     # ./spec/features/footer_spec.rb:11:in `block (2 levels) in <top (required)>'

  9) footer footer is on home page
     Failure/Error: expect(page).to have_css 'footer'
       expected to find css "footer" but there were no matches
     # ./spec/features/footer_spec.rb:7:in `block (2 levels) in <top (required)>'

  10) products admin user editing product
      Failure/Error: click_link 'Edit'
      
      Capybara::ElementNotFound:
        Unable to find link "Edit"
      # ./spec/features/admin/products_spec.rb:33:in `block (3 levels) in <top (required)>'

  11) crop wranglers signed in wrangler can create a new crop
      Failure/Error: click_link wrangler.login_name
      
      Capybara::ElementNotFound:
        Unable to find link "wrangler1"
      # ./spec/features/crops/crop_wranglers_spec.rb:44:in `block (3 levels) in <top (required)>'

  12) crop wranglers signed in wrangler can see list of crops with extra detail of who created a crop
      Failure/Error: click_link wrangler.login_name
      
      Capybara::ElementNotFound:
        Unable to find link "wrangler4"
      # ./spec/features/crops/crop_wranglers_spec.rb:28:in `block (3 levels) in <top (required)>'

  13) crop wranglers signed in wrangler sees crop wranglers listed on the crop wrangler page
      Failure/Error: click_link wrangler.login_name
      
      Capybara::ElementNotFound:
        Unable to find link "wrangler7"
      # ./spec/features/crops/crop_wranglers_spec.rb:15:in `block (3 levels) in <top (required)>'

  14) crop wranglers signed in non-wrangler can't see wrangling page with js
      Failure/Error: click_link member.login_name
      
      Capybara::ElementNotFound:
        Unable to find link "member329"
      # ./spec/features/crops/crop_wranglers_spec.rb:80:in `block (3 levels) in <top (required)>'

  15) layouts/application.html.haml includes the analytics code
      Failure/Error: = tag("meta", property: "og:title",
      
      ActionView::Template::Error:
        no implicit conversion of nil into String
      # ./app/views/layouts/_meta.html.haml:8:in `+'
      # ./app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_47366130038800'
      # ./app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml__2096314005913121334_47366127166220'
      # ./spec/views/layouts/application_spec.rb:22:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # TypeError:
      #   no implicit conversion of nil into String
      #   ./app/views/layouts/_meta.html.haml:8:in `+'

  16) follows when signed in following another member removes members from following and followers lists after unfollow
      Failure/Error: expect(page).not_to have_content other_member.login_name.to_s
        expected not to find text "member381" in "Skip navigation menu Search crop database: Crops Community member380 Sign out member380's follows × Close Unfollowed member381 No entries found No entries found"
      # ./spec/features/following_spec.rb:78:in `block (4 levels) in <top (required)>'

  17) follows when signed in following another member has correct message and follow button after unfollow
      Failure/Error: expect(page).to have_content "Unfollowed #{other_member.login_name}"
        expected to find text "Unfollowed member385" in "TypeError in Home#index Showing /home/shadja/Documents/ruby on rails/growstuff/app/views/layouts/_meta.html.haml where line #8 raised: no implicit conversion of nil into String Extracted source (around line #8): 6 7 8 9 10 11 - else = tag(\"meta\", property: \"og:image\", content: image_url('facebook-thumbnail.png')) = tag(\"meta\", property: \"og:title\", content: (content_for?(:title) ? yield(:title) + \" - \" : \"\") + ENV['GROWSTUFF_SITE_NAME']) = tag(\"meta\", property: \"og:type\", content: \"website\") = tag(\"meta\", property: \"og:url\", content: root_url) Trace of template inclusion: app/views/layouts/application.html.haml Rails.root: /home/shadja/Documents/ruby on rails/growstuff Application Trace | Framework Trace | Full Trace app/views/layouts/_meta.html.haml:8:in `+' app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_70240701838720' app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml__2096314005913121334_70240701925040' Request Parameters: None Toggle session dump Toggle env dump Response Headers: None". (However, . it was found 1 time including non-visible text.)
      # ./spec/features/following_spec.rb:57:in `block (4 levels) in <top (required)>'

  18) layouts/_meta.html.haml should have a title
      Failure/Error: = tag("meta", property: "og:title",
      
      ActionView::Template::Error:
        no implicit conversion of nil into String
      # ./app/views/layouts/_meta.html.haml:8:in `+'
      # ./app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_47366124070960'
      # ./spec/views/layouts/_meta_spec.rb:17:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # TypeError:
      #   no implicit conversion of nil into String
      #   ./app/views/layouts/_meta.html.haml:8:in `+'

  19) layouts/_meta.html.haml should have a Posts RSS feed
      Failure/Error: = tag("meta", property: "og:title",
      
      ActionView::Template::Error:
        no implicit conversion of nil into String
      # ./app/views/layouts/_meta.html.haml:8:in `+'
      # ./app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_47366124070960'
      # ./spec/views/layouts/_meta_spec.rb:17:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # TypeError:
      #   no implicit conversion of nil into String
      #   ./app/views/layouts/_meta.html.haml:8:in `+'

  20) layouts/_meta.html.haml should have a Crops RSS feed
      Failure/Error: = tag("meta", property: "og:title",
      
      ActionView::Template::Error:
        no implicit conversion of nil into String
      # ./app/views/layouts/_meta.html.haml:8:in `+'
      # ./app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_47366124070960'
      # ./spec/views/layouts/_meta_spec.rb:17:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # TypeError:
      #   no implicit conversion of nil into String
      #   ./app/views/layouts/_meta.html.haml:8:in `+'

  21) layouts/_meta.html.haml should have a Plantings RSS feed
      Failure/Error: = tag("meta", property: "og:title",
      
      ActionView::Template::Error:
        no implicit conversion of nil into String
      # ./app/views/layouts/_meta.html.haml:8:in `+'
      # ./app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_47366124070960'
      # ./spec/views/layouts/_meta_spec.rb:17:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # TypeError:
      #   no implicit conversion of nil into String
      #   ./app/views/layouts/_meta.html.haml:8:in `+'

  22) seeds signed in user button on front page to add seeds
      Failure/Error: click_link "Add seeds"
      
      Capybara::ElementNotFound:
        Unable to find link "Add seeds"
      # ./spec/features/seeds/misc_seeds_spec.rb:22:in `block (3 levels) in <top (required)>'

  23) account types admin user adding an account type
      Failure/Error: expect(page).to have_content 'Account type was successfully created'
        expected to find text "Account type was successfully created" in "TypeError in AccountTypes#show Showing /home/shadja/Documents/ruby on rails/growstuff/app/views/layouts/_meta.html.haml where line #8 raised: no implicit conversion of nil into String Extracted source (around line #8): 6 7 8 9 10 11 - else = tag(\"meta\", property: \"og:image\", content: image_url('facebook-thumbnail.png')) = tag(\"meta\", property: \"og:title\", content: (content_for?(:title) ? yield(:title) + \" - \" : \"\") + ENV['GROWSTUFF_SITE_NAME']) = tag(\"meta\", property: \"og:type\", content: \"website\") = tag(\"meta\", property: \"og:url\", content: root_url) Trace of template inclusion: app/views/layouts/application.html.haml Rails.root: /home/shadja/Documents/ruby on rails/growstuff Application Trace | Framework Trace | Full Trace app/views/layouts/_meta.html.haml:8:in `+' app/views/layouts/_meta.html.haml:8:in `_app_views_layouts__meta_html_haml___4153046369539732852_70240701838720' app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml__2096314005913121334_70240701925040' app/controllers/account_types_controller.rb:14:in `show' Request Parameters: {\"id\"=>\"10\"} Toggle session dump Toggle env dump Response Headers: None". (However, . it was found 1 time including non-visible text.)
      # ./spec/features/admin/account_types_spec.rb:38:in `block (3 levels) in <top (required)>'

  24) account types admin user navigating to account type admin with JavaScript on
      Failure/Error: click_link member.login_name
      
      Capybara::ElementNotFound:
        Unable to find link "member418"
      # ./spec/features/admin/account_types_spec.rb:15:in `block (3 levels) in <top (required)>'

  25) account types admin user editing account type
      Failure/Error: click_link 'Edit'
      
      Capybara::ElementNotFound:
        Unable to find link "Edit"
      # ./spec/features/admin/account_types_spec.rb:43:in `block (3 levels) in <top (required)>'

  26) account types admin user deleting account type
      Failure/Error: click_link 'Delete'
      
      Capybara::ElementNotFound:
        Unable to find link "Delete"
      # ./spec/features/admin/account_types_spec.rb:53:in `block (3 levels) in <top (required)>'

  27) account types admin user navigating to account type admin without JavaScript - Accessility version
      Failure/Error: click_link "Admin"
      
      Capybara::ElementNotFound:
        Unable to find link "Admin"
      # ./spec/features/admin/account_types_spec.rb:25:in `block (3 levels) in <top (required)>'

  28) signin with facebook sign in
      Failure/Error: first('.signup a').click
      
      NoMethodError:
        undefined method `click' for nil:NilClass
      # ./spec/features/signin_spec.rb:84:in `block (3 levels) in <top (required)>'

Top 3 slowest examples (30.53 seconds, 10.5% of total time):
  signup sign up for new account with existing username
    10.45 seconds ./spec/features/signup_spec.rb:16
  follows when signed in following another member has correct message and follow button after unfollow
    10.28 seconds ./spec/features/following_spec.rb:54
  Notifications pagination paginates at 30 notifications per page
    9.79 seconds ./spec/features/notifications_spec.rb:43

Top 3 slowest example groups:
  Notifications
    8.69 seconds average (34.76 seconds / 4 examples) ./spec/features/notifications_spec.rb:3
  follows
    8.31 seconds average (41.56 seconds / 5 examples) ./spec/features/following_spec.rb:3
  Changing locales
    8.01 seconds average (8.01 seconds / 1 example) ./spec/features/locale_spec.rb:3

Finished in 4 minutes 49.4 seconds (files took 6.13 seconds to load)
173 examples, 28 failures
```

**Comment by pozorvlak** [comment]
Huh, very strange. @shadjachaudhari, are there any files with names ending in `.png` under the `tmp/capybara` directory in your Growstuff checkout? If so, could you post one here?

**Comment by shadjachaudhari** [comment]
![screenshot_sign-in_2017-07-07-15-57-12 673](https://user-images.githubusercontent.com/27852691/28007938-0828e74e-6573-11e7-87ab-b2036cb44573.png)

this is latest png file.

**Comment by milesgould** [comment]
OK, it looks like the `GROWSTUFF_SITE_NAME` environment variable hasn't been set. Try copying the file `config/application.yml.example` to `config/application.yml` and running the tests again. That should have been mentioned in the [New Contributor Guide](https://github.com/Growstuff/growstuff/wiki/New-contributor-guide) - sorry!

**Comment by Br3nda** [comment]
@shadjachaudhari Any further updates? Can we close this?
