### ISSUE TITLE
Deploys are broken

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1396]
```
0.30s$ bundle exec script/heroku_maintenance.rb on
bundler: failed to load command: script/heroku_maintenance.rb (script/heroku_maintenance.rb)
LoadError: cannot load such file -- heroku-api
  script/heroku_maintenance.rb:3:in `require'
  script/heroku_maintenance.rb:3:in `<top (required)>'
The command "bundle exec script/heroku_maintenance.rb on" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by Br3nda** [comment]
duplicate of #1389
