### ISSUE TITLE
Deploy broken at assets:precompile.

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1780]
WARNING on line 123 of /tmp/build_42101bdc80be2274450f68fb784ca377/app/assets/stylesheets/overrides.sass:

       This selector doesn't have any properties and will not be rendered.

       

       WARNING on line 10 of /tmp/build_42101bdc80be2274450f68fb784ca377/app/assets/stylesheets/predictions.sass:

       This selector doesn't have any properties and will not be rendered.

on heroku:

```
       rake aborted!

       Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

       /tmp/build_42101bdc80be2274450f68fb784ca377/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:234:in `parse_result'

       /tmp/build_42101bdc80be2274450f68fb784ca377/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:216:in `run_uglifyjs'

       /tmp/build_42101bdc80be2274450f68fb784ca377/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:168:in `compile'
```

**Comment by Br3nda** [comment]
I haven't been able to reproduce this on dev yet. I've started work on branch:fix-deploy.

Any ideas? I'm running out of them

**Comment by Br3nda** [comment]
I've changed production.rb to use
`config.assets.js_compressor = Uglifier.new(harmony: true)`

see:
0b6aca4295a0f4fc7a38b4b065796dab13331134

Still getting this error
AFAIK, there is no ES6 syntax in the app anywhere.

**Comment by Br3nda** [comment]
git bisect says it was introduced in this commit
a43c2354233053d130d539050450ea0a6fce9505

**Comment by CloCkWeRX** [comment]
Let's back that commit out then, and maybe try just upgrading comfortable mexican sofa to 2.0 (to rule out it having ES6 syntax in some asset); though I'm betting its https://github.com/comfy/comfortable-mexican-sofa/issues/832

**Comment by Br3nda** [comment]
@CloCkWeRX you're correct. I removed the gem, the initialiser and the routes for Comfy Mexican Sofa and now it works.

**Comment by Br3nda** [comment]
I'm outta ideas. I've filed a bug report at https://github.com/comfy/comfortable-mexican-sofa/issues/864

**Comment by CloCkWeRX** [comment]
Any chance that asset compilation is not happening in RAILS_ENV=production,
but in an another env (rails_env=staging?) so the uglifier initializer
isn't used?

Or the initializer isnt included early enough to take effect?

**Comment by Br3nda** [comment]
How about we disable the cms for a while and get this released.

**Comment by cesy** [comment]
Sounds good to me.
