### ISSUE TITLE
plantings that have errors on display (production)

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2374]
plantings that have errors on display (production)
https://www.growstuff.org/plantings/midiprincess-raised-bed-1-fava-bean
https://www.growstuff.org/plantings/midiprincess-in-ground-bed-1-brussels-sprouts

errors in log:
```
2020-01-11T21:01:30.279006+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d] Completed 500 Internal Server Error in 24ms (ActiveRecord: 9.6ms)
2020-01-11T21:01:30.279556+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d]
2020-01-11T21:01:30.279632+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d] NoMethodError (undefined method `+' for nil:NilClass):
2020-01-11T21:01:30.279634+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d]
2020-01-11T21:01:30.279639+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d] app/models/planting.rb:116:in `nearby_same_crop'
2020-01-11T21:01:30.279641+00:00 app[web.1]: [d6d11c77-1631-453e-870c-38e9f49a816d] app/controllers/plantings_controller.rb:31:in `show'
```

**Comment by Br3nda** [comment]
Fixed
