### ISSUE TITLE
routing / cms error on growstuff-apple-touch-icon-precomposed

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2718]
Errors in the production logs - looking for a file called  `growstuff-apple-touch-icon-precomposed`, and the request is routed to the CMS (comfy Mexican sofa)

```
="121.99.217.170" dyno=web.1 connect=2ms service=4ms status=200 bytes=1129 protocol=https
2021-01-03T20:07:33.709950+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc]
2021-01-03T20:07:33.709966+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] ActionController::RoutingError (Page Not Found at: "growstuff-apple-touch-icon-precomposed"):
2021-01-03T20:07:33.709966+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc]
2021-01-03T20:07:33.709967+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] comfortable_mexican_sofa (2.0.19) app/controllers/comfy/cms/content_controller.rb:68:in `load_cms_page'
2021-01-03T20:07:33.709968+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `block in make_lambda'
2021-01-03T20:07:33.709969+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] activesupport (6.0.3.2) lib/active_support/callbacks.rb:181:in `block (2 levels) in halting_and_conditional'
2021-01-03T20:07:33.709970+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
2021-01-03T20:07:33.709970+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] activesupport (6.0.3.2) lib/active_support/callbacks.rb:182:in `block in halting_and_conditional'
2021-01-03T20:07:33.709971+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `block in invoke_before'
2021-01-03T20:07:33.709972+00:00 app[web.1]: [9f3ab525-86e2-4740-8fe8-0584869537bc] activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `each
```

**Comment by CloCkWeRX** [comment]
```
app/views/layouts/_head.html.haml
33:  %link{ href: "/growstuff-apple-touch-icon-precomposed.png", rel: "apple-touch-icon-precomposed" }
```
