### ISSUE TITLE
Flickr photo import is broken on production

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2719]
```
2021-01-03T20:09:45.098528+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f]
2021-01-03T20:09:45.098542+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] FlickRaw::FailedResponse ('flickr.reflection.getMethods' - Invalid API Key (Key not found)):
2021-01-03T20:09:45.098543+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f]
2021-01-03T20:09:45.098544+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] app/models/concerns/member_flickr.rb:14:in `new'
2021-01-03T20:09:45.098544+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] app/models/concerns/member_flickr.rb:14:in `flickr'
2021-01-03T20:09:45.098545+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] app/models/concerns/member_flickr.rb:47:in `flickr_sets'
2021-01-03T20:09:45.098546+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] app/controllers/photos_controller.rb:100:in `retrieve_from_flickr'
2021-01-03T20:09:45.098547+00:00 app[web.1]: [9bcd2c04-65a9-40ca-9d47-53a3bb515e0f] app/controllers/photos_controller.rb:32:in `new'
```

**Comment by Br3nda** [comment]
Looks like the old flickr account (formally known as Skud's) has been deleted (more likely removed because of inactivity)

I'll roll new API keys. All users will need to re-authenticate with Flickr

**Comment by Br3nda** [comment]
i saved a copy of the old keys into my secret storing app (can retrieve if we need them)


I made my own API key and loaded into production. We're getting further, instead of "Invalid API Key (Key not found)" we now have "FlickRaw::FailedResponse ('flickr.photosets.getList' - Invalid auth token)"

We'll need to detect this and redirect the user to re-authenticate
