### ISSUE TITLE
Can't add new crops

### ISSUE THREAD

**Issue by corviday** [Growstuff/growstuff#2847]
Thank you for creating an incredibly useful site!

I am unable to suggest new crops from the [new crops form](https://www.growstuff.org/crops/new). When I press the 'Save' button, I get a message saying, "We're sorry, but something went wrong."

**Comment by dcyoung-dev** [comment]
This may also be an issue connected to emails not being sent in #2883

**Comment by cesy** [comment]
Yes, reproduced on staging and it's due to the SendGrid email issues.

**Comment by cesy** [comment]
On staging, now we've updated to MailGun and added myself as an authorised recipient, and added myself as a crop wrangler, it looks like this now works. We should make sure we have a couple of active crop wranglers on production when we fix emails.

**Comment by CloCkWeRX** [comment]
Need to mark required in the new crop form:
```
2023-03-13T03:25:29.574480+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7] ActionController::ParameterMissing (param is missing or the value is empty: alt_name):
2023-03-13T03:25:29.574481+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7]
2023-03-13T03:25:29.574482+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7] app/controllers/crops_controller.rb:190:in `names_params'
2023-03-13T03:25:29.574482+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7] app/controllers/crops_controller.rb:150:in `save_crop_names'
2023-03-13T03:25:29.574482+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7] app/controllers/crops_controller.rb:103:in `block in create'
2023-03-13T03:25:29.574483+00:00 app[web.1]: [7bd653e9-8c03-4b60-bb6e-5ae7d763f3a7] app/controllers/crops_controller.rb:103:in `create'
```

**Comment by CloCkWeRX** [comment]
![image](https://user-images.githubusercontent.com/365751/224601356-908abb6e-f485-4b07-b1c8-ef475955ffcf.png)

**Comment by CloCkWeRX** [comment]
Split to #3278
