### ISSUE TITLE
Codespace minor points

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#3315]
When I load up a new codespace now that everything is merged, it now complains if I try rails s until I do rvm install 3.1.3. It then wants me to do bundle install, which also fails with an error about pg. So although it worked in the codespace branch, somehow it now doesn't work in dev branch, or I'm doing something wrong?

**Comment by cesy** [comment]
It also needed rvm use 3.1.3 and then didn't recognise the command rails - I'm missing something obvious here. Rbenv had 3.1.3 already, so clearly it's looking at the system or at rvm. Even when system, rvm and rbenv all have 3.1.3, bundler complains that it's 3.1.4.

Did I remember rake db:create? Should I try ./bin/rails server instead of rails s?

sudo mkdir /usr/bin/mkdir doesn't solve the pg issue. sudo gem install pg -v 1.5.1 does work, and then the rest of bundle install goes further but still fails. sudo bundle install gives dire warnings and won't run.

**Comment by CloCkWeRX** [comment]
```
@CloCkWeRX ➜ /workspaces/growstuff (dev) $ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
@CloCkWeRX ➜ /workspaces/growstuff (dev) $ bundle
Following files may not be writable, so sudo is needed:
  /usr/local/rvm/gems/default
  /usr/local/rvm/gems/default/bin
  /usr/local/rvm/gems/default/bin
  /usr/local/rvm/gems/default/build_info
  /usr/local/rvm/gems/default/cache
  /usr/local/rvm/gems/default/doc
  /usr/local/rvm/gems/default/extensions
  /usr/local/rvm/gems/default/gems
  /usr/local/rvm/gems/default/plugins
  /usr/local/rvm/gems/default/specifications
Your Ruby version is 3.1.4, but your Gemfile specified 3.1.3
```
I suspect at the time of the PR, I was focused on 3.1.4

**Comment by CloCkWeRX** [comment]
For some reason, when I bundled the first time, pg didn't install.
```
$ git checkout CloCkWeRX-patch-1
$ bundle

@CloCkWeRX ➜ /workspaces/growstuff (CloCkWeRX-patch-1) $ bundle exec rake db:create
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /usr/local/rvm/gems/default/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980:in `new'
Database 'growstuff_dev' already exists
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /usr/local/rvm/gems/default/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980:in `new'
```
Happy enough

**Comment by CloCkWeRX** [comment]
```
@CloCkWeRX ➜ /workspaces/growstuff (CloCkWeRX-patch-1) $ bundle exec rails s -b 0.0.0.0
=> Booting Puma
=> Rails 7.0.4.3 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.2.2 (ruby 3.1.4-p223) ("Speaking of Now")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 11030
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```

Takes it sweet time, but:
![image](https://user-images.githubusercontent.com/365751/234829536-b77d466c-9f96-400d-9263-c61f68e29ad1.png)

**Comment by cesy** [comment]
Bizarre - I'm still getting the error. Will try again on a fresh branch.

**Comment by cesy** [comment]
Brand new codespace on dev branch:
```
@cesy ➜ /workspaces/growstuff (dev) $ bundle
Following files may not be writable, so sudo is needed:
  /usr/local/rvm/gems/default
  /usr/local/rvm/gems/default/bin
  /usr/local/rvm/gems/default/bin
  /usr/local/rvm/gems/default/build_info
  /usr/local/rvm/gems/default/cache
  /usr/local/rvm/gems/default/doc
  /usr/local/rvm/gems/default/extensions
  /usr/local/rvm/gems/default/gems
  /usr/local/rvm/gems/default/plugins
  /usr/local/rvm/gems/default/specifications
Your Ruby version is 3.1.4, but your Gemfile specified 3.1.3
```

**Comment by cesy** [comment]
Bizarre, but the uplift to ruby 3.1.4 seems to have solved it.
