### ISSUE TITLE
Uncaught TypeError: ((ft.event.special[o.origType] || {}).handle || o.handler).apply is not a function

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3558]
```
application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:39 Uncaught TypeError: ((ft.event.special[o.origType] || {}).handle || o.handler).apply is not a function
    at HTMLDocument.dispatch (application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:39:3005)
    at g.handle (application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:38:32441)
dispatch @ application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:39
g.handle @ application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:38
3application-a90108109956824e2c2230031c24c21754b0b3d6b0765e5c6a75373705b4e6c1.js:39 Uncaught TypeError: ((ft.event.special[o.origType] || {}).handle || o.handler).apply is
```

Reproduce steps
Type in any input or on any page

Expected:
No errors

Actual:
The bootstrap dropdown? handler is attempting to fire
![image](https://github.com/Growstuff/growstuff/assets/365751/bea0bbd0-6ea2-49b4-b1c0-d6279c150939)

**Comment by CloCkWeRX** [comment]
From bootstrap-accessibility:
```on("keydown.bs.dropdown.data-api",toggle+", [role=menu]"```

This element doesn't exist, so it won't bind.

**Comment by CloCkWeRX** [comment]
Fixed in dev
