### ISSUE TITLE
Adding Photos to a Plant Results in a 500 

### ISSUE THREAD

**Issue by hopeman15** [Growstuff/growstuff#3691]
While trying to add a photo to my plant, I was confronted with a 500-server error. I could successfully connect to Flickr and see my picture, but when I select it, I get the error. 

| Image Connected via Flickr | 500 Error |
|----------------|--------------|
|<img width="256" alt="Screenshot 2024-03-25 at 20 53 21" src="https://github.com/Growstuff/growstuff/assets/7081242/c64876ff-1ca9-4fc6-91a5-1fdced8ab62a">|<img width="694" alt="Screenshot 2024-03-25 at 20 53 27" src="https://github.com/Growstuff/growstuff/assets/7081242/5591cd8f-243b-4a1c-8477-976f63fa5aed">|

**Comment by CloCkWeRX** [comment]
Oh, that's interesting! Flickr keeps sending me menacing emails about account limits, so may be tricky for me to reproduce. I will have a look at logs shortly

**Comment by CloCkWeRX** [comment]
From staging, logs:
```
&photo%5Bsource%5D=flickr&photo%5Bsource_id%5D=34692094943&type=planting" host=growstuff-staging.herokuapp.com request_id=391482e3-c1a5-eb12-cda1-a6ad9a2c8e31 fwd="149.167.22.60" dyno=web.1 connect=0ms service=415ms status=500 bytes=949 protocol=http1.1 tls=true tls_version=unknown
2025-09-01T16:17:32.813705+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31]   [1m[36mTRANSACTION (0.7ms)[0m  [1m[31mROLLBACK[0m
2025-09-01T16:17:32.814279+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] Completed 500 Internal Server Error in 410ms (ActiveRecord: 5.2ms (5 queries, 0 cached) | GC: 0.3ms)
2025-09-01T16:17:32.815320+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31]   
2025-09-01T16:17:32.815321+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] NoMethodError (undefined method `name' for nil):
2025-09-01T16:17:32.815321+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31]   
2025-09-01T16:17:32.815321+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] app/models/photo.rb:52:in `flickr_metadata'
2025-09-01T16:17:32.815322+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] app/models/photo.rb:80:in `set_flickr_metadata!'
2025-09-01T16:17:32.815322+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] app/controllers/photos_controller.rb:90:in `find_or_create_photo_from_flickr_photo'
2025-09-01T16:17:32.815322+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] app/controllers/photos_controller.rb:43:in `block in create'
2025-09-01T16:17:32.815323+00:00 app[web.1]: [391482e3-c1a5-eb12-cda1-a6ad9a2c8e31] app/controllers/photos_controller.rb:42:in `create'
2025-09-01T16:17:37.023351+00:00 heroku[router]: at=info method=GET path="/members/wrangler1/plantings" host=www.staging.growstuff.org request_id=03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de fwd="54.84.147.79" dyno=web.1 connect=0ms service=38ms status=500 bytes=949 protocol=http1.1 tls=true tls_version=unknown
2025-09-01T16:17:36.986119+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] Started GET "/members/wrangler1/plantings" for 54.84.147.79 at 2025-09-01 16:17:36 +0000
2025-09-01T16:17:36.987108+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] Processing by PlantingsController#index as HTML
2025-09-01T16:17:36.987125+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Parameters: {"member_slug"=>"wrangler1"}
2025-09-01T16:17:36.991838+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   [1m[36mMember Load (1.0ms)[0m  [1m[34mSELECT "members".* FROM "members" WHERE "members"."slug" = $1 LIMIT $2[0m  [["slug", "wrangler1"], ["LIMIT", 1]]
2025-09-01T16:17:36.993051+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendering layout layouts/application.html.haml
2025-09-01T16:17:36.993098+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendering plantings/index.html.haml within layouts/application
2025-09-01T16:17:36.994052+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered shared/_signin_signup.html.haml (Duration: 0.1ms | GC: 0.0ms)
2025-09-01T16:17:36.994141+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered layouts/_nav.haml (Duration: 0.4ms | GC: 0.0ms)
2025-09-01T16:17:36.999864+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered members/_member.haml (Duration: 5.3ms | GC: 0.0ms) [cache hit]
2025-09-01T16:17:37.015960+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   [1m[33mPlanting Search (15.4ms)[0m  plantings_production/_search {"query":{"function_score":{"functions":[{"field_value_factor":{"field":"created_at","factor":1.0,"modifier":"ln2p"},"filter":{"exists":{"field":"created_at"}}}],"query":{"bool":{"must":{"match_all":{}},"filter":[{"term":{"active":{"value":true}}},{"term":{"owner_id":{"value":139}}}]}},"score_mode":"sum"}},"timeout":"11000ms","size":30}
2025-09-01T16:17:37.018210+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered plantings/_badges.html.haml (Duration: 0.0ms | GC: 0.0ms)
2025-09-01T16:17:37.018315+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered plantings/_progress.html.haml (Duration: 0.0ms | GC: 0.0ms)
2025-09-01T16:17:37.018730+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered plantings/_card.html.haml (Duration: 2.4ms | GC: 0.0ms)
2025-09-01T16:17:37.018805+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered plantings/index.html.haml within layouts/application (Duration: 25.7ms | GC: 0.0ms)
2025-09-01T16:17:37.018830+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   Rendered layout layouts/application.html.haml (Duration: 25.8ms | GC: 0.0ms)
2025-09-01T16:17:37.018996+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] Completed 500 Internal Server Error in 32ms (Searchkick: 15.4ms | ActiveRecord: 1.0ms (1 query, 0 cached) | GC: 0.2ms)
2025-09-01T16:17:37.020634+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   
2025-09-01T16:17:37.020635+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"gardens", :member_slug=>"wrangler1", :slug=>nil}, possible unmatched constraints: [:slug]):
2025-09-01T16:17:37.020635+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] 
2025-09-01T16:17:37.020637+00:00 app[web.1]: Causes:
2025-09-01T16:17:37.020637+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"gardens", :member_slug=>"wrangler1", :slug=>nil}, possible unmatched constraints: [:slug])
2025-09-01T16:17:37.020637+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]     37:         = link_to member_path(slug: planting.owner_slug), class: "owner-link" do
2025-09-01T16:17:37.020638+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]     38:           = planting.owner_login_name
2025-09-01T16:17:37.020638+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]     39:         in
2025-09-01T16:17:37.020639+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]     40:         = link_to garden_path(slug: planting.garden_slug), class: "garden-link" do
2025-09-01T16:17:37.020639+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]     41:           = planting.garden_name
2025-09-01T16:17:37.020639+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de]   
2025-09-01T16:17:37.020639+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] app/views/plantings/_card.html.haml:40
2025-09-01T16:17:37.020640+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] app/views/plantings/_card.html.haml:1
2025-09-01T16:17:37.020640+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] app/views/plantings/index.html.haml:46
2025-09-01T16:17:37.020640+00:00 app[web.1]: [03ff0c71-92b5-5f00-9ef4-5fc4ffc2f5de] 
```

**Comment by CloCkWeRX** [comment]
Took a bit, but it was a silly type casting error.
