### ISSUE TITLE
RSpec output contains Capybara warnings

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#928]
```
$ rspec spec/features
/home/miles/src/growstuff/spec/rails_helper.rb:11:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 6410
............*..........................................................................................Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member506-garden-magic-bean"]
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member506-garden-magic-bean-52173c1a-287d-4050-af12-8565855b0a69"]
.Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member509-magic-bean"]
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member509-magic-bean-35bb80a1-c19c-47f3-b358-c8a68764ca2c"]
................................................................................Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://en.wikipedia.org/wiki/Magic_bean"]
...........................................
```

This isn't an actual problem, but it is annoying.

**Comment by pozorvlak** [comment]
I have found the culprit:

```
$ rspec spec/features/planting_reminder_spec.rb 
/home/miles/src/growstuff/spec/rails_helper.rb:11:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 7233

Planting reminder email
  has a greeting
  when member has no plantings
    tells you to track your plantings
    doesn't list plantings
  when member has no harvests
    doesn't list plantings
    tells you to tracking plantings
  when member has some harvests
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member6-magic-bean"]
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member6-magic-bean-592fe44d-8d94-44f7-9d5a-d42aecc44e8c"]
    lists harvests
  when member has some plantings
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member9-garden-magic-bean"]
Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member9-garden-magic-bean-13f1778f-33d5-42fc-9544-da51485a0c36"]
    lists plantings
```
